"""Cambio a 1 sola tabla

Revision ID: c2d98f709e8c
Revises: 7ff4db0c21cd
Create Date: 2023-02-10 18:38:03.384656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d98f709e8c'
down_revision = '7ff4db0c21cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('raza', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=20), nullable=True),
    sa.Column('DNI', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
